version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
  postgre:
    image: 'postgres:10'
    restart: always
    environment:
      - DEBUG=false
      - DB_USER='postgres'
      - DB_PASS='postgres'
      - DB_NAME='postgres'
    networks:
      - app-network
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: flags_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: 123qwe
    networks:
      - app-network
  mongo:
    image: mongo:3.4
    command: [--smallfiles]
    networks:
      - app-network
  nginx:
    image: nginx:1.15.5
    volumes:
      - "./nginx/app.conf:/etc/nginx/conf.d/default.conf"
      - ./app/templates:/front:ro
    restart: on-failure
    networks:
      - app-network
    ports:
      - "80:80"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


