[database]

DB_HOST = 'postgre'
DB_PORT = 5432

DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASS = 'postgres'

REDIS_HOST = 'redis'
REDIS_PORT = 6379

MONGO_HOST = 'mongo'
MONGO_PORT = 27017
MAX_POOL_SIZE = 5

MONGO_DB_NAME = 'flags_shop'

MYSQL_HOST = 'mysql'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASSWORD = '123qwe'
MYSQL_DB_NAME = 'flags_shop'